### ISSUE TITLE
🙏

### ISSUE THREAD

**Issue by Inihzay** [ginny100/Meta-Back-End-Developer#2]
Hello ginny100 thank you for all your meta back end developer assignments answers it was very useful. Can u pls upload the remaining topic assignment answers it would be really helpful because I can't complete some of the topic and there is deadline near. Thank you and pls ignore my broken English.

**Comment by ginny100** [comment]
Hi there,

Sorry, I have not reached those remaining topics just yet, I have been extremely busy with my job and other projects so far. I don't know when I will be able to accomplish the whole professional certificate, it all depends on my schedule and how much free time I can spend working on this repo. I can't promise it could be anytime soon.

I'm sure you can still complete those assignments without me uploading mine. If you're stuck, be sure to utilize the forum on Coursera, it's very helpful for me as well as other learners. Good luck! 🍀
