### ISSUE TITLE
Rest of the Course

### ISSUE THREAD

**Issue by gimpoco1** [ginny100/Meta-Back-End-Developer#4]
Hi ginny100,
I am currently enrolled to the Meta Back-End Dev on Coursera and I found your codes interesting for my learning path.
Just wanted to know if you will be able to upload the rest of the courses as well (e.g Django, API, etc) .
I would be really glad if you could do that. 
thank you in advance

**Comment by AdiRaushan** [comment]
hy ginny i really liked your repo on meta course well i have a request from can you please upload the whole course of it it will really helpful

**Comment by MuhammadAliNiz** [comment]
@AdiRaushan @gimpoco1 have you complete django course? if you completed then can you can you help by providing Source code?

**Comment by cd155** [comment]
Does anyone know where I can find Django Web Framework and API. Currently, I am auditing the course.
